-------------------------------=-------------------------
-- Database: crowdfunding_db 
---------------------------------------------------------

-- This is a database for crowdfunding campaigns

-- The below sql will create the database crowdfunding_db
-- Dropping the database will not work if there
-- are any connections to it.  All PIDs that
-- are connected must be terminated in some fashion
-- before the drop.  EXTREME caution should be
-- exercised in dropping an existing database
-- and that should not be done in a production environment.
--
-- This code is generated by PgAdmin4 when the database
-- is created using the GUI, with the appropriate field entries.

-- DROP DATABASE IF EXISTS crowdfunding_db;

CREATE DATABASE crowdfunding_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

COMMENT ON DATABASE crowdfunding_db
    IS 'Project 2 crowdfunding database';

-